### API Limits 
* Max 100 results per page, default is 20
* Basic access is granted automatically after collecting a few details and will allow you to make up to 1,000 requests/day, with a rate limit of 50 requests/second. If you need more bandwidth, you can request more once you have your basic key.
* Access tokens expire in 3600 seconds (1 hour)

In [1]:
import requests
from config import CLIENTID
from config import CLIENTSECRET
# import petpy as Petfinder
from datetime import datetime
import pandas as pd
import json
from pandas.io.json import json_normalize
import matplotlib.pyplot as plt 
from IPython.display import Image, display, Markdown
import time

### Connecting to PetFinder API

In [2]:
credentials = {
  'grant_type': 'client_credentials',
  'client_id': {CLIENTID},
  'client_secret': {CLIENTSECRET}
}

token_response = requests.post('https://api.petfinder.com/v2/oauth2/token', data=credentials)
access_token = token_response.json()['access_token']

data_auth = {
    'Authorization': f'Bearer {access_token}',
}

# Example GET request 
# data_response = requests.get('https://api.petfinder.com/v2/{CATEGORY}/{ACTION}?{parameter_1}={value_1}', headers=data_auth)
startTime = datetime.now()

# time to check start of access token 
print(startTime)

2019-05-18 10:19:35.490359

In [3]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/types?"
# add_type = "&type="
# add_breed = "&breed="
# add_city = "&city="
# end_url = "&page=1&limit=2"
# target_url = base_url + add_type + "dog" + add_breed + "pug" + end_url
data_response = requests.get(base_url, headers=data_auth)
data_response.json() # this is a dictionary 

# convert nested json to dataframe

{'types': [{'name': 'Dog',
   'coats': ['Hairless', 'Short', 'Medium', 'Long', 'Wire', 'Curly'],
   'colors': ['Apricot / Beige',
    'Bicolor',
    'Black',
    'Brindle',
    'Brown / Chocolate',
    'Golden',
    'Gray / Blue / Silver',
    'Harlequin',
    'Merle (Blue)',
    'Merle (Red)',
    'Red / Chestnut / Orange',
    'Sable',
    'Tricolor (Brown, Black, & White)',
    'White / Cream',
    'Yellow / Tan / Blond / Fawn'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/dog'},
    'breeds': {'href': '/v2/types/dog/breeds'}}},
  {'name': 'Cat',
   'coats': ['Hairless', 'Short', 'Medium', 'Long'],
   'colors': ['Black',
    'Black & White / Tuxedo',
    'Blue Cream',
    'Blue Point',
    'Brown / Chocolate',
    'Buff & White',
    'Buff / Tan / Fawn',
    'Calico',
    'Chocolate Point',
    'Cream / Ivory',
    'Cream Point',
    'Dilute Calico',
    'Dilute Tortoiseshell',
    'Flame Point',
    'Gray & White',
    'Gray / Blue / Silver',
    'Lilac Point',
    'Orange & White',
    'Orange / Red',
    'Seal Point',
    'Smoke',
    'Tabby (Brown / Chocolate)',
    'Tabby (Buff / Tan / Fawn)',
    'Tabby (Gray / Blue / Silver)',
    'Tabby (Leopard / Spotted)',
    'Tabby (Orange / Red)',
    'Tabby (Tiger Striped)',
    'Torbie',
    'Tortoiseshell',
    'White'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/cat'},
    'breeds': {'href': '/v2/types/cat/breeds'}}},
  {'name': 'Rabbit',
   'coats': ['Short', 'Long'],
   'colors': ['Agouti',
    'Black',
    'Blue / Gray',
    'Brown / Chocolate',
    'Cream',
    'Lilac',
    'Orange / Red',
    'Sable',
    'Silver Marten',
    'Tan',
    'Tortoiseshell',
    'White'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/rabbit'},
    'breeds': {'href': '/v2/types/rabbit/breeds'}}},
  {'name': 'Small & Furry',
   'coats': ['Hairless', 'Short', 'Long'],
   'colors': ['Agouti',
    'Albino',
    'Black',
    'Black Sable',
    'Blue / Gray',
    'Brown / Chocolate',
    'Calico',
    'Champagne',
    'Cinnamon',
    'Cream',
    'Orange / Red',
    'Sable',
    'Tan',
    'Tortoiseshell',
    'White',
    'White (Dark-Eyed)'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/small-furry'},
    'breeds': {'href': '/v2/types/small-furry/breeds'}}},
  {'name': 'Horse',
   'coats': [],
   'colors': ['Appaloosa',
    'Bay',
    'Bay Roan',
    'Black',
    'Blue Roan',
    'Brown',
    'Buckskin',
    'Champagne',
    'Chestnut / Sorrel',
    'Cremello',
    'Dapple Gray',
    'Dun',
    'Gray',
    'Grullo',
    'Liver',
    'Paint',
    'Palomino',
    'Perlino',
    'Piebald',
    'Pinto',
    'Red Roan',
    'Silver Bay',
    'Silver Buckskin',
    'Silver Dapple',
    'White'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/horse'},
    'breeds': {'href': '/v2/types/horse/breeds'}}},
  {'name': 'Bird',
   'coats': [],
   'colors': ['Black',
    'Blue',
    'Brown',
    'Buff',
    'Gray',
    'Green',
    'Olive',
    'Orange',
    'Pink',
    'Purple / Violet',
    'Red',
    'Rust / Rufous',
    'Tan',
    'White',
    'Yellow'],
   'genders': ['Male', 'Female', 'Unknown'],
   '_links': {'self': {'href': '/v2/types/bird'},
    'breeds': {'href': '/v2/types/bird/breeds'}}},
  {'name': 'Scales, Fins & Other',
   'coats': [],
   'colors': ['Black',
    'Blue',
    'Brown',
    'Gray',
    'Green',
    'Iridescent',
    'Orange',
    'Purple',
    'Red',
    'Tan',
    'White',
    'Yellow'],
   'genders': ['Male', 'Female', 'Unknown'],
   '_links': {'self': {'href': '/v2/types/scales-fins-other'},
    'breeds': {'href': '/v2/types/scales-fins-other/breeds'}}},
  {'name': 'Barnyard',
   'coats': ['Short', 'Long'],
   'colors': ['Agouti',
    'Black',
    'Black & White',
    'Brindle',
    'Brown',
    'Gray',
    'Pink',
    'Red',
    'Roan',
    'Spotted',
    'Tan',
    'White'],
   'genders': ['Male', 'Female'],
   '_links': {'self': {'href': '/v2/types/barnyard'},
    'breeds': {'href': '/v2/types/barnyard/breeds'}}}]}

## PetFinder API Dog Breeds

In [4]:
dogbreed_url = "https://api.petfinder.com/v2/types/dog/breeds?"
dog_response = requests.get(dogbreed_url, headers=data_auth)
dogbreed_dict = dog_response.json()
dogbreed_dict

{'breeds': [{'name': 'Affenpinscher',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Afghan Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Airedale Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Akbash', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Akita', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Alaskan Malamute', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Bulldog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Eskimo Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Foxhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Hairless Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Staffordshire Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'American Water Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Anatolian Shepherd',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Appenzell Mountain Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Australian Cattle Dog / Blue Heeler',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Australian Kelpie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Australian Shepherd',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Australian Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Basenji', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Basset Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Beagle', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bearded Collie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Beauceron', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bedlington Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Belgian Shepherd / Laekenois',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Belgian Shepherd / Malinois',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Belgian Shepherd / Sheepdog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Belgian Shepherd / Tervuren',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bernese Mountain Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bichon Frise', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Black and Tan Coonhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Black Labrador Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Black Mouth Cur', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Black Russian Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bloodhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Blue Lacy', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bluetick Coonhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Boerboel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bolognese', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Border Collie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Border Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Borzoi', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Boston Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bouvier des Flandres',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Boxer', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Boykin Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Briard', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Brittany Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Brussels Griffon', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bull Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Bullmastiff', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cairn Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Canaan Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cane Corso', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cardigan Welsh Corgi',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Carolina Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Catahoula Leopard Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cattle Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Caucasian Sheepdog / Caucasian Ovtcharka',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cavalier King Charles Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chesapeake Bay Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chihuahua', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chinese Crested Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chinese Foo Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chinook', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chocolate Labrador Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Chow Chow', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': "Cirneco dell'Etna", '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Clumber Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cockapoo', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Cocker Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Collie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Coonhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Corgi', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Coton de Tulear', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Curly-Coated Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dachshund', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dalmatian', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dandie Dinmont Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Doberman Pinscher', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dogo Argentino', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dogue de Bordeaux', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Dutch Shepherd', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Bulldog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Cocker Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Coonhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Foxhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Pointer', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Setter', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Shepherd', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Springer Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'English Toy Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Entlebucher', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Eskimo Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Feist', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Field Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Fila Brasileiro', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Finnish Lapphund', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Finnish Spitz', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Flat-Coated Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Fox Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Foxhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'French Bulldog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Galgo Spanish Greyhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'German Pinscher', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'German Shepherd Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'German Shorthaired Pointer',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'German Spitz', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'German Wirehaired Pointer',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Giant Schnauzer', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Glen of Imaal Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Golden Retriever', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Gordon Setter', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Great Dane', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Great Pyrenees', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Greater Swiss Mountain Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Greyhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Hamiltonstovare', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Harrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Havanese', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Hovawart', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Husky', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Ibizan Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Icelandic Sheepdog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Illyrian Sheepdog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Irish Setter', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Irish Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Irish Water Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Irish Wolfhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Italian Greyhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Jack Russell Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Japanese Chin', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Jindo', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Kai Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Karelian Bear Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Keeshond', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Kerry Blue Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Kishu', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Klee Kai', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Komondor', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Kuvasz', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Kyi Leo', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Labrador Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Lakeland Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Lancashire Heeler', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Leonberger', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Lhasa Apso', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Lowchen', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Maltese', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Manchester Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Maremma Sheepdog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Mastiff', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'McNab', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Miniature Bull Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Miniature Dachshund',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Miniature Pinscher',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Miniature Poodle', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Miniature Schnauzer',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Mixed Breed', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Mountain Cur', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Mountain Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Munsterlander', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Neapolitan Mastiff',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'New Guinea Singing Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Newfoundland Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Norfolk Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Norwegian Buhund', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Norwegian Elkhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Norwegian Lundehund',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Norwich Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Nova Scotia Duck Tolling Retriever',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Old English Sheepdog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Otterhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Papillon', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Parson Russell Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Patterdale Terrier / Fell Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pekingese', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pembroke Welsh Corgi',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Peruvian Inca Orchid',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Petit Basset Griffon Vendeen',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pharaoh Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pit Bull Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Plott Hound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pointer', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Polish Lowland Sheepdog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pomeranian', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Poodle', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Portuguese Podengo',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Portuguese Water Dog',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Presa Canario', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pug', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Puli', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pumi', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Pyrenean Shepherd', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Rat Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Redbone Coonhound', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Retriever', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Rhodesian Ridgeback',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Rottweiler', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Rough Collie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Saint Bernard', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Saluki', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Samoyed', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Sarplaninac', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Schipperke', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Schnauzer', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Scottish Deerhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Scottish Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Sealyham Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Setter', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Shar-Pei', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Sheep Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Shepherd', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Shetland Sheepdog / Sheltie',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Shiba Inu', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Shih Tzu', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Siberian Husky', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Silky Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Skye Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Sloughi', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Smooth Collie', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Smooth Fox Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'South Russian Ovtcharka',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Spanish Water Dog', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Spinone Italiano', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Spitz', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Staffordshire Bull Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Standard Poodle', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Standard Schnauzer',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Sussex Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Swedish Vallhund', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Thai Ridgeback', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Tibetan Mastiff', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Tibetan Spaniel', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Tibetan Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Tosa Inu', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Toy Fox Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Toy Manchester Terrier',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Treeing Walker Coonhound',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Vizsla', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Weimaraner', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Welsh Springer Spaniel',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Welsh Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'West Highland White Terrier / Westie',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Wheaten Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Whippet', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'White German Shepherd',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Wire Fox Terrier', '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Wirehaired Dachshund',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Wirehaired Pointing Griffon',
   '_links': {'type': {'href': '/v2/types/dog'}}},
  {'name': 'Wirehaired Terrier',

In [5]:
dogbreed_df = pd.DataFrame.from_dict(dogbreed_dict, orient='columns')
dogbreed_df2 = dogbreed_df['breeds']

secondtry = {k:v for k,v in dogbreed_df2.items()}

PetFinder_DogBreeds = []
for item in dogbreed_df2:
    PetFinder_DogBreeds.append(item["name"])

In [6]:
PetFinder_DogBreeds

['Affenpinscher',
 'Afghan Hound',
 'Airedale Terrier',
 'Akbash',
 'Akita',
 'Alaskan Malamute',
 'American Bulldog',
 'American Eskimo Dog',
 'American Foxhound',
 'American Hairless Terrier',
 'American Staffordshire Terrier',
 'American Water Spaniel',
 'Anatolian Shepherd',
 'Appenzell Mountain Dog',
 'Australian Cattle Dog / Blue Heeler',
 'Australian Kelpie',
 'Australian Shepherd',
 'Australian Terrier',
 'Basenji',
 'Basset Hound',
 'Beagle',
 'Bearded Collie',
 'Beauceron',
 'Bedlington Terrier',
 'Belgian Shepherd / Laekenois',
 'Belgian Shepherd / Malinois',
 'Belgian Shepherd / Sheepdog',
 'Belgian Shepherd / Tervuren',
 'Bernese Mountain Dog',
 'Bichon Frise',
 'Black and Tan Coonhound',
 'Black Labrador Retriever',
 'Black Mouth Cur',
 'Black Russian Terrier',
 'Bloodhound',
 'Blue Lacy',
 'Bluetick Coonhound',
 'Boerboel',
 'Bolognese',
 'Border Collie',
 'Border Terrier',
 'Borzoi',
 'Boston Terrier',
 'Bouvier des Flandres',
 'Boxer',
 'Boykin Spaniel',
 'Briard',
 'Brittany Spaniel',
 'Brussels Griffon',
 'Bull Terrier',
 'Bullmastiff',
 'Cairn Terrier',
 'Canaan Dog',
 'Cane Corso',
 'Cardigan Welsh Corgi',
 'Carolina Dog',
 'Catahoula Leopard Dog',
 'Cattle Dog',
 'Caucasian Sheepdog / Caucasian Ovtcharka',
 'Cavalier King Charles Spaniel',
 'Chesapeake Bay Retriever',
 'Chihuahua',
 'Chinese Crested Dog',
 'Chinese Foo Dog',
 'Chinook',
 'Chocolate Labrador Retriever',
 'Chow Chow',
 "Cirneco dell'Etna",
 'Clumber Spaniel',
 'Cockapoo',
 'Cocker Spaniel',
 'Collie',
 'Coonhound',
 'Corgi',
 'Coton de Tulear',
 'Curly-Coated Retriever',
 'Dachshund',
 'Dalmatian',
 'Dandie Dinmont Terrier',
 'Doberman Pinscher',
 'Dogo Argentino',
 'Dogue de Bordeaux',
 'Dutch Shepherd',
 'English Bulldog',
 'English Cocker Spaniel',
 'English Coonhound',
 'English Foxhound',
 'English Pointer',
 'English Setter',
 'English Shepherd',
 'English Springer Spaniel',
 'English Toy Spaniel',
 'Entlebucher',
 'Eskimo Dog',
 'Feist',
 'Field Spaniel',
 'Fila Brasileiro',
 'Finnish Lapphund',
 'Finnish Spitz',
 'Flat-Coated Retriever',
 'Fox Terrier',
 'Foxhound',
 'French Bulldog',
 'Galgo Spanish Greyhound',
 'German Pinscher',
 'German Shepherd Dog',
 'German Shorthaired Pointer',
 'German Spitz',
 'German Wirehaired Pointer',
 'Giant Schnauzer',
 'Glen of Imaal Terrier',
 'Golden Retriever',
 'Gordon Setter',
 'Great Dane',
 'Great Pyrenees',
 'Greater Swiss Mountain Dog',
 'Greyhound',
 'Hamiltonstovare',
 'Harrier',
 'Havanese',
 'Hound',
 'Hovawart',
 'Husky',
 'Ibizan Hound',
 'Icelandic Sheepdog',
 'Illyrian Sheepdog',
 'Irish Setter',
 'Irish Terrier',
 'Irish Water Spaniel',
 'Irish Wolfhound',
 'Italian Greyhound',
 'Jack Russell Terrier',
 'Japanese Chin',
 'Jindo',
 'Kai Dog',
 'Karelian Bear Dog',
 'Keeshond',
 'Kerry Blue Terrier',
 'Kishu',
 'Klee Kai',
 'Komondor',
 'Kuvasz',
 'Kyi Leo',
 'Labrador Retriever',
 'Lakeland Terrier',
 'Lancashire Heeler',
 'Leonberger',
 'Lhasa Apso',
 'Lowchen',
 'Maltese',
 'Manchester Terrier',
 'Maremma Sheepdog',
 'Mastiff',
 'McNab',
 'Miniature Bull Terrier',
 'Miniature Dachshund',
 'Miniature Pinscher',
 'Miniature Poodle',
 'Miniature Schnauzer',
 'Mixed Breed',
 'Mountain Cur',
 'Mountain Dog',
 'Munsterlander',
 'Neapolitan Mastiff',
 'New Guinea Singing Dog',
 'Newfoundland Dog',
 'Norfolk Terrier',
 'Norwegian Buhund',
 'Norwegian Elkhound',
 'Norwegian Lundehund',
 'Norwich Terrier',
 'Nova Scotia Duck Tolling Retriever',
 'Old English Sheepdog',
 'Otterhound',
 'Papillon',
 'Parson Russell Terrier',
 'Patterdale Terrier / Fell Terrier',
 'Pekingese',
 'Pembroke Welsh Corgi',
 'Peruvian Inca Orchid',
 'Petit Basset Griffon Vendeen',
 'Pharaoh Hound',
 'Pit Bull Terrier',
 'Plott Hound',
 'Pointer',
 'Polish Lowland Sheepdog',
 'Pomeranian',
 'Poodle',
 'Portuguese Podengo',
 'Portuguese Water Dog',
 'Presa Canario',
 'Pug',
 'Puli',
 'Pumi',
 'Pyrenean Shepherd',
 'Rat Terrier',
 'Redbone Coonhound',
 'Retriever',
 'Rhodesian Ridgeback',
 'Rottweiler',
 'Rough Collie',
 'Saint Bernard',
 'Saluki',
 'Samoyed',
 'Sarplaninac',
 'Schipperke',
 'Schnauzer',
 'Scottish Deerhound',
 'Scottish Terrier',
 'Sealyham Terrier',
 'Setter',
 'Shar-Pei',
 'Sheep Dog',
 'Shepherd',
 'Shetland Sheepdog / Sheltie',
 'Shiba Inu',
 'Shih Tzu',
 'Siberian Husky',
 'Silky Terrier',
 'Skye Terrier',
 'Sloughi',
 'Smooth Collie',
 'Smooth Fox Terrier',
 'South Russian Ovtcharka',
 'Spaniel',
 'Spanish Water Dog',
 'Spinone Italiano',
 'Spitz',
 'Staffordshire Bull Terrier',
 'Standard Poodle',
 'Standard Schnauzer',
 'Sussex Spaniel',
 'Swedish Vallhund',
 'Terrier',
 'Thai Ridgeback',
 'Tibetan Mastiff',
 'Tibetan Spaniel',
 'Tibetan Terrier',
 'Tosa Inu',
 'Toy Fox Terrier',
 'Toy Manchester Terrier',
 'Treeing Walker Coonhound',
 'Vizsla',
 'Weimaraner',
 'Welsh Springer Spaniel',
 'Welsh Terrier',
 'West Highland White Terrier / Westie',
 'Wheaten Terrier',
 'Whippet',
 'White German Shepherd',
 'Wire Fox Terrier',
 'Wirehaired Dachshund',
 'Wirehaired Pointing Griffon',
 'Wirehaired Terrier',
 'Xoloitzcuintli / Mexican Hairless',
 'Yellow Labrador Retriever',
 'Yorkshire Terrier']

In [7]:
# breeds_list_df = pd.read_excel('top_breeds_excel.xlsx', index_col=0)
# breeds_list_df.head()

In [39]:
top_breeds_df = pd.read_excel('top_breeds_excel.xlsx', index_col=0)
top_breeds_df.head(20)

                             Breed  Rank
1            Retrievers (Labrador)     1
2             German Shepherd Dogs     2
3              Retrievers (Golden)     3
4                  French Bulldogs     4
5                         Bulldogs     5
6                          Beagles     6
7                          Poodles     7
8                      Rottweilers     8
9    Pointers (German Shorthaired)     9
10              Yorkshire Terriers    10
11                          Boxers    11
12                      Dachshunds    12
13           Pembroke Welsh Corgis    13
14                Siberian Huskies    14
15            Australian Shepherds    15
16                     Great Danes    16
17              Doberman Pinschers    17
18  Cavalier King Charles Spaniels    18
19            Miniature Schnauzers    19
20                        Shih Tzu    20

In [25]:
# fake_bank_data_csv = "DDATransactions_9815000000000_0486830300000000.csv"

top_cities_df = pd.read_csv("best_cities.csv", names=['Rank','City','Total Score','Pet Budget Rank','Pet Health and Wellness Rank','Outdoor Pet Friendliness Rank'], header=-1)
top_cities_df.head()

# index=['Rank','City','Total Score','Pet Budget Rank','Pet Health and Wellness Rank','Outdoor Pet Friendliness Rank']

,Rank,City,Total Score,Pet Budget Rank,Pet Health and Wellness Rank,Outdoor Pet Friendliness Rank
0,1,"Scottsdale, AZ",60.48,80,1,4
1,2,"Orlando, FL",58.35,14,4,46
2,3,"San Diego, CA",58.10,78,3,6
3,4,"Austin, TX",56.20,33,2,58
4,5,"Phoenix, AZ",56.00,49,13,16

In [37]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/animals?"
add_type = "&type="
add_breed = "&breed="
add_city = "&city="
end_url = "&page=1&limit=20"
# for breed in PetFinder_DogBreeds:
# target_url = base_url + add_type + "dog" + add_breed + PetFinder_DogBreeds[16] + add_city + "Austin" + end_url
target_url = base_url + add_type + "dog" + add_breed + "Retriever" + end_url
# time.sleep(2)
data_response1 = requests.get(target_url, headers=data_auth)
# time.sleep(2)
json_response1 = data_response1.json() # this is a dictionary 
# json_response1

In [38]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/animals?"
add_type = "&type="
add_breed = "&breed="
add_city = "&city="
end_url = "&page=1&limit=20"
# for breed in PetFinder_DogBreeds:
# target_url = base_url + add_type + "dog" + add_breed + PetFinder_DogBreeds[16] + add_city + "Austin" + end_url
target_url = base_url + add_type + "dog" + add_breed + "Yorkshire Terrier" + end_url
# time.sleep(2)
data_response2 = requests.get(target_url, headers=data_auth)
# time.sleep(2)
json_response2 = data_response2.json() # this is a dictionary 
# json_response2

In [42]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/animals?"
add_type = "&type="
add_breed = "&breed="
add_city = "&city="
end_url = "&page=1&limit=20"
# for breed in PetFinder_DogBreeds:
# target_url = base_url + add_type + "dog" + add_breed + PetFinder_DogBreeds[16] + add_city + "Austin" + end_url
target_url = base_url + add_type + "dog" + add_breed + "Dachshund" + end_url
# time.sleep(2)
data_response3 = requests.get(target_url, headers=data_auth)
# time.sleep(2)
json_response3 = data_response3.json() # this is a dictionary 
# json_response3

In [44]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/animals?"
add_type = "&type="
add_breed = "&breed="
add_city = "&city="
end_url = "&page=1&limit=20"
# for breed in PetFinder_DogBreeds:
# target_url = base_url + add_type + "dog" + add_breed + PetFinder_DogBreeds[16] + add_city + "Austin" + end_url
target_url = base_url + add_type + "dog" + add_breed + "Rottweiler" + end_url
# time.sleep(2)
data_response4 = requests.get(target_url, headers=data_auth)
# time.sleep(2)
json_response4 = data_response4.json() # this is a dictionary 
# json_response4

In [46]:
# parameters = {animal_type:"dog" , breed: "pug", }
base_url = "https://api.petfinder.com/v2/animals?"
add_type = "&type="
add_breed = "&breed="
add_city = "&city="
end_url = "&page=1&limit=20"
# for breed in PetFinder_DogBreeds:
# target_url = base_url + add_type + "dog" + add_breed + PetFinder_DogBreeds[16] + add_city + "Austin" + end_url
target_url = base_url + add_type + "dog" + add_breed + "Boxer" + end_url
# time.sleep(2)
data_response5 = requests.get(target_url, headers=data_auth)
# time.sleep(2)
json_response5 = data_response5.json() # this is a dictionary 
# json_response5

In [47]:
id_input = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

In [10]:
# first_breed = PetFinder_DogBreeds[0]

In [49]:
type(json_response1)

dict

In [50]:
list(json_response1.keys())[0]

'animals'

In [51]:
json_normalize(json_response1)

,animals,pagination._links.next.href,pagination.count_per_page,pagination.current_page,pagination.total_count,pagination.total_pages
0,"[{'id': 44730107, 'organization_id': 'CA628', ...",/v2/animals?breed=Retriever&limit=20&page=2&ty...,20,1,66612,3331

In [52]:
breed1_df = json_normalize(json_response1)
breed1_df['animals'][0][0]['id']

44730107

In [57]:
breed2_df = json_normalize(json_response2)
breed2_df['animals'][0][0]['id']

44729062

In [58]:
breed3_df = json_normalize(json_response3)
breed3_df['animals'][0][0]['id']

44730263

In [59]:
breed4_df = json_normalize(json_response4)
breed4_df['animals'][0][0]['id']

44729771

In [60]:
breed5_df = json_normalize(json_response5)
breed5_df['animals'][0][0]['id']

44730260

In [65]:
dog_ids = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_ids.append(breed1_df['animals'][0][id_item]['id'])
    dog_ids.append(breed2_df['animals'][0][id_item]['id'])
    dog_ids.append(breed3_df['animals'][0][id_item]['id'])
    dog_ids.append(breed4_df['animals'][0][id_item]['id'])
    dog_ids.append(breed5_df['animals'][0][id_item]['id'])

dog_ids[0]

44730107

In [66]:
dog_names = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_names.append(breed1_df['animals'][0][id_item]['name'])
    dog_names.append(breed2_df['animals'][0][id_item]['name'])
    dog_names.append(breed3_df['animals'][0][id_item]['name'])
    dog_names.append(breed4_df['animals'][0][id_item]['name'])
    dog_names.append(breed5_df['animals'][0][id_item]['name'])

dog_names[0]

'Jasper'

In [67]:
dog_status = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_status.append(breed1_df['animals'][0][id_item]['status'])
    dog_status.append(breed2_df['animals'][0][id_item]['status'])
    dog_status.append(breed3_df['animals'][0][id_item]['status'])
    dog_status.append(breed4_df['animals'][0][id_item]['status'])
    dog_status.append(breed5_df['animals'][0][id_item]['status'])

dog_status[0]

'adoptable'

In [68]:
is_spayed = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    is_spayed.append(breed1_df['animals'][0][id_item]['attributes']['spayed_neutered'])
    is_spayed.append(breed2_df['animals'][0][id_item]['attributes']['spayed_neutered'])
    is_spayed.append(breed3_df['animals'][0][id_item]['attributes']['spayed_neutered'])
    is_spayed.append(breed4_df['animals'][0][id_item]['attributes']['spayed_neutered'])
    is_spayed.append(breed5_df['animals'][0][id_item]['attributes']['spayed_neutered'])

is_spayed[0]

False

In [69]:
is_house_trained = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    is_house_trained.append(breed1_df['animals'][0][id_item]['attributes']['house_trained'])
    is_house_trained.append(breed2_df['animals'][0][id_item]['attributes']['house_trained'])
    is_house_trained.append(breed3_df['animals'][0][id_item]['attributes']['house_trained'])
    is_house_trained.append(breed4_df['animals'][0][id_item]['attributes']['house_trained'])
    is_house_trained.append(breed5_df['animals'][0][id_item]['attributes']['house_trained'])

is_house_trained[0]

False

In [70]:
is_declawed = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    is_declawed.append(breed1_df['animals'][0][id_item]['attributes']['declawed'])
    is_declawed.append(breed2_df['animals'][0][id_item]['attributes']['declawed'])
    is_declawed.append(breed3_df['animals'][0][id_item]['attributes']['declawed'])
    is_declawed.append(breed4_df['animals'][0][id_item]['attributes']['declawed'])
    is_declawed.append(breed5_df['animals'][0][id_item]['attributes']['declawed'])

is_declawed[0]

In [71]:
has_special_needs = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    has_special_needs.append(breed1_df['animals'][0][id_item]['attributes']['special_needs'])
    has_special_needs.append(breed2_df['animals'][0][id_item]['attributes']['special_needs'])
    has_special_needs.append(breed3_df['animals'][0][id_item]['attributes']['special_needs'])
    has_special_needs.append(breed4_df['animals'][0][id_item]['attributes']['special_needs'])
    has_special_needs.append(breed5_df['animals'][0][id_item]['attributes']['special_needs'])

has_special_needs[0]

False

In [72]:
shots_current = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    shots_current.append(breed1_df['animals'][0][id_item]['attributes']['shots_current'])
    shots_current.append(breed2_df['animals'][0][id_item]['attributes']['shots_current'])
    shots_current.append(breed3_df['animals'][0][id_item]['attributes']['shots_current'])
    shots_current.append(breed4_df['animals'][0][id_item]['attributes']['shots_current'])
    shots_current.append(breed5_df['animals'][0][id_item]['attributes']['shots_current'])

shots_current[0]

False

In [73]:
dog_street_address = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_street_address.append(breed1_df['animals'][0][id_item]['contact']['address']['address1'])
    dog_street_address.append(breed2_df['animals'][0][id_item]['contact']['address']['address1'])
    dog_street_address.append(breed3_df['animals'][0][id_item]['contact']['address']['address1'])
    dog_street_address.append(breed4_df['animals'][0][id_item]['contact']['address']['address1'])
    dog_street_address.append(breed5_df['animals'][0][id_item]['contact']['address']['address1'])

dog_street_address[0]

'14269 Road 28'

In [74]:
dog_address_country = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_address_country.append(breed1_df['animals'][0][id_item]['contact']['address']['country'])
    dog_address_country.append(breed2_df['animals'][0][id_item]['contact']['address']['country'])
    dog_address_country.append(breed3_df['animals'][0][id_item]['contact']['address']['country'])
    dog_address_country.append(breed4_df['animals'][0][id_item]['contact']['address']['country'])
    dog_address_country.append(breed5_df['animals'][0][id_item]['contact']['address']['country'])

dog_address_country[0]

'US'

In [75]:
dog_address_state = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_address_state.append(breed1_df['animals'][0][id_item]['contact']['address']['state'])
    dog_address_state.append(breed2_df['animals'][0][id_item]['contact']['address']['state'])
    dog_address_state.append(breed3_df['animals'][0][id_item]['contact']['address']['state'])
    dog_address_state.append(breed4_df['animals'][0][id_item]['contact']['address']['state'])
    dog_address_state.append(breed5_df['animals'][0][id_item]['contact']['address']['state'])

dog_address_state[0]

'CA'

In [76]:
dog_address_city = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_address_city.append(breed1_df['animals'][0][id_item]['contact']['address']['city'])
    dog_address_city.append(breed2_df['animals'][0][id_item]['contact']['address']['city'])
    dog_address_city.append(breed3_df['animals'][0][id_item]['contact']['address']['city'])
    dog_address_city.append(breed4_df['animals'][0][id_item]['contact']['address']['city'])
    dog_address_city.append(breed5_df['animals'][0][id_item]['contact']['address']['city'])

dog_address_city[0]

'Madera'

In [77]:
dog_gender = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_gender.append(breed1_df['animals'][0][id_item]['gender'])
    dog_gender.append(breed2_df['animals'][0][id_item]['gender'])
    dog_gender.append(breed3_df['animals'][0][id_item]['gender'])
    dog_gender.append(breed4_df['animals'][0][id_item]['gender'])
    dog_gender.append(breed5_df['animals'][0][id_item]['gender'])

dog_gender[0]

'Male'

In [78]:
dog_age = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_age.append(breed1_df['animals'][0][id_item]['age'])
    dog_age.append(breed2_df['animals'][0][id_item]['age'])
    dog_age.append(breed3_df['animals'][0][id_item]['age'])
    dog_age.append(breed4_df['animals'][0][id_item]['age'])
    dog_age.append(breed5_df['animals'][0][id_item]['age'])

dog_age[0]

'Young'

In [83]:
breed1_df['animals'][0][0]['breeds']['primary']

'Retriever'

In [84]:
breed1_df['animals'][0][0]['breeds']['secondary']

'Mixed Breed'

In [88]:
dog_breed1 = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_breed1.append(breed1_df['animals'][0][0]['breeds']['primary'])
    dog_breed1.append(breed2_df['animals'][0][0]['breeds']['primary'])
    dog_breed1.append(breed3_df['animals'][0][0]['breeds']['primary'])
    dog_breed1.append(breed4_df['animals'][0][0]['breeds']['primary'])
    dog_breed1.append(breed5_df['animals'][0][0]['breeds']['primary'])

dog_breed1[0]

'Retriever'

In [89]:
dog_breed2 = []
# id_input = [0,1,2,3,4,5,6,7,8,9]

for id_item in id_input:
    dog_breed2.append(breed1_df['animals'][0][0]['breeds']['secondary'])
    dog_breed2.append(breed2_df['animals'][0][0]['breeds']['secondary'])
    dog_breed2.append(breed3_df['animals'][0][0]['breeds']['secondary'])
    dog_breed2.append(breed4_df['animals'][0][0]['breeds']['secondary'])
    dog_breed2.append(breed5_df['animals'][0][0]['breeds']['secondary'])

dog_breed2[0]

'Mixed Breed'

In [92]:
# create dataframe
dogs_df = pd.DataFrame({
    "id": dog_ids,
    "name": dog_names,
    "dog_status": dog_status,
    "is_spayed": is_spayed,
    "is_house_trained": is_house_trained,
    "is_declawed": is_declawed,
    "has_special_needs": has_special_needs,
    "shots_current": shots_current,
    "address": dog_street_address,
    "country": dog_address_country,
    "state": dog_address_state,
    "city": dog_address_city,
    "gender": dog_gender,
    "age": dog_age,
    "primary breed": dog_breed1,
    "secondary breed": dog_breed2
})

dogs_df.head()

,id,name,dog_status,is_spayed,is_house_trained,is_declawed,has_special_needs,shots_current,address,country,state,city,gender,age,primary breed,secondary breed
0,44730107,Jasper,adoptable,False,False,None,False,False,14269 Road 28,US,CA,Madera,Male,Young,Retriever,Mixed Breed
1,44729062,Nugget,adoptable,False,False,None,False,False,6725 Randolph Road,US,WA,Moses Lake,Male,Senior,Yorkshire Terrier,Mixed Breed
2,44730263,Carl,adoptable,True,False,None,False,True,1700 Mardi Gras Blvd.,US,LA,New Orleans,Male,Baby,Dachshund,None
3,44729771,JAKE,adoptable,True,False,None,False,False,4750 West South Range Rd.,US,OH,Canfield,Male,Young,Rottweiler,Mixed Breed
4,44730260,puppies,adoptable,False,False,None,False,True,32423 Calle Perfecto,US,CA,San Juan Capistrano,Female,Baby,Boxer,Shepherd

In [93]:
dogs_df.head(100)

,id,name,dog_status,is_spayed,is_house_trained,is_declawed,has_special_needs,shots_current,address,country,state,city,gender,age,primary breed,secondary breed
0,44730107,Jasper,adoptable,False,False,None,False,False,14269 Road 28,US,CA,Madera,Male,Young,Retriever,Mixed Breed
1,44729062,Nugget,adoptable,False,False,None,False,False,6725 Randolph Road,US,WA,Moses Lake,Male,Senior,Yorkshire Terrier,Mixed Breed
2,44730263,Carl,adoptable,True,False,None,False,True,1700 Mardi Gras Blvd.,US,LA,New Orleans,Male,Baby,Dachshund,None
3,44729771,JAKE,adoptable,True,False,None,False,False,4750 West South Range Rd.,US,OH,Canfield,Male,Young,Rottweiler,Mixed Breed
4,44730260,puppies,adoptable,False,False,None,False,True,32423 Calle Perfecto,US,CA,San Juan Capistrano,Female,Baby,Boxer,Shepherd
5,44730088,Lilly,adoptable,False,False,None,False,False,1412 1st NE,US,GA,Moultrie,Female,Baby,Retriever,Mixed Breed
6,44728800,Snickers,adopted,True,False,None,False,True,None,US,TX,Dallas,Male,Adult,Yorkshire Terrier,Mixed Breed
7,44730129,Snitch,adoptable,True,False,None,False,True,1520 W. Mingus Ave.,US,AZ,Cottonwood,Male,Adult,Dachshund,None
8,44729434,STAR,adoptable,False,False,None,False,False,612 Canino Rd,US,TX,Houston,Female,Adult,Rottweiler,Mixed Breed
9,44729980,CONCHO,adoptable,False,False,None,False,False,7610 Davis Blvd,US,FL,Naples,Male,Adult,Boxer,Shepherd
10,44729168,Ruby,adoptable,True,False,None,False,True,43 Ratley Rd,US,AL,Ashland,Female,Adult,Retriever,Mixed Breed
11,44728249,Freddie,adoptable,True,False,None,False,True,None,US,PA,Walnutport,Male,Adult,Yorkshire Terrier,Mixed Breed
12,44730130,Bludger,adoptable,True,False,None,False,True,1520 W. Mingus Ave.,US,AZ,Cottonwood,Male,Adult,Dachshund,None
13,44729288,SOPHIA,adoptable,True,False,None,False,False,2811 SE 29th Street,US,OK,Oklahoma City,Female,Adult,Rottweiler,Mixed Breed
14,44729888,Dallas,adoptable,True,False,None,False,True,3410 S. Walnut Street,US,IN,Bloomington,Male,Young,Boxer,Shepherd
15,44729634,Jax Cole,adoptable,True,False,None,False,True,6003 Chapel Hill Road Ste. 133,US,NC,Raleigh,Male,Baby,Retriever,Mixed Breed
16,44728082,Puzzles,adoptable,True,False,None,False,True,32 Shelter Circle,US,DE,Camden,Female,Adult,Yorkshire Terrier,Mixed Breed
17,44730131,Mac,adoptable,True,False,None,False,True,1520 W. Mingus Ave.,US,AZ,Cottonwood,Male,Adult,Dachshund,None
18,44729012,BOOBAH,adoptable,False,False,None,False,False,3031 N Erie Ave,US,OK,Tulsa,Male,Young,Rottweiler,Mixed Breed
19,44729837,COMANCHI,adoptable,True,False,None,False,False,2080 S. Quebec St.,US,CO,Denver,Male,Adult,Boxer,Shepherd
20,44729635,Bella Blue,adoptable,True,False,None,False,True,6003 Chapel Hill Road Ste. 133,US,NC,Raleigh,Female,Baby,Retriever,Mixed Breed
21,44728063,FINN,adoptable,True,False,None,False,False,4000 N. Silverbell RD,US,AZ,Tucson,Male,Adult,Yorkshire Terrier,Mixed Breed
22,44730132,Cheese,adoptable,True,False,None,False,True,1520 W. Mingus Ave.,US,AZ,Cottonwood,Female,Adult,Dachshund,None
23,44728902,A490681,adoptable,False,False,None,False,False,3750 Brown Station Rd,US,MD,Upper Marlboro,Male,Adult,Rottweiler,Mixed Breed
24,44729838,SPIRIT,adoptable,True,False,None,False,False,2080 S. Quebec St.,US,CO,Denver,Female,Young,Boxer,Shepherd
25,44728413,Coco,adoptable,False,False,None,False,False,305 Airport Road,US,SC,Greenville,Female,Baby,Retriever,Mixed Breed
26,44727995,A978262,adoptable,True,False,None,False,False,7115 De Castro Road,US,FL,Winter Haven,Male,Young,Yorkshire Terrier,Mixed Breed
27,44730018,REESE,adoptable,True,False,None,False,False,1601 Eubanks Road,US,NC,Chapel Hill,Male,Young,Dachshund,None
28,44728896,BRUTUS,adoptable,True,False,None,False,False,3750 Brown Station Rd,US,MD,Upper Marlboro,Male,Adult,Rottweiler,Mixed Breed
29,44729839,LUKE,adoptable,True,False,None,False,False,2080 S. Quebec St.,US,CO,Denver,Male,Baby,Boxer,Shepherd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,44727231,Alfalfa,adoptable,True,False,None,False,True,3355 Berkmar Dr.,US,VA,Charlottesville,Male,Baby,Retriever,Mixed Breed
71,44726210,CURLY,adoptable,True,False,None,False,False,21417 Dunham Road,US,MI,Clinton Township,Male,Adult,Yorkshire Terrier,Mixed Breed
72,44728497,KIKI,adoptable,True,False,None,False,False,1705 S. Hanley,US,MO,Saint Louis,Male,Young,Dachshund,None
73,44727278,Joe,adoptable,True,False,None,False,False,14444 Okeechobee Blvd.,US,FL,Loxahatchee,Male,Young,Rottweiler,Mixed Breed
74,44728945,McCartney,adoptable,True,False,None,False,True,None,US,CO,Littleton,Male,Baby,Boxer,Shepherd
75,44727232,Buckwheat,adoptable,True,False,None,False,True,3355 Berkmar Dr.,US,VA,Charlottesville,Male,Baby,Retriever,Mixed Breed
76,44726195,JASMINE,adoptable,False,False,None,False,True,7049 Baker Blvd,US,TX,Richland Hills,Female,Adult,Yorkshire Terrier,Mixed Breed
77,44728442,Zoe,adoptable,True,True,None,False,True,4400 Audubon Lane,US,MS,Gautier,Female,Young,Dachshund,None
78,44726139,Theia,adoptable,True,False,None,True,False,616 N. Spring St.,US,TN,Clarksville,Female,Young,Rottweiler,Mixed Breed
79,44728950,Starkey,adoptable,True,False,None,False,True,None,US,CO,Littleton,Male,Baby,Boxer,Shepherd
80,44727096,41708650,adoptable,False,False,None,False,False,328 Furman Hall Road,US,SC,Greenville,Female,Adult,Retriever,Mixed Breed
81,44726196,JASPER,adoptable,False,False,None,False,True,7049 Baker Blvd,US,TX,Richland Hills,Male,Adult,Yorkshire Terrier,Mixed Breed
82,44728328,Koda,adoptable,False,False,None,False,False,2050 Spindletop Rd,US,TX,Beaumont,Male,Adult,Dachshund,None
83,44725902,Arya,adoptable,True,False,None,False,False,None,US,CA,Rancho Santa Margarita,Female,Baby,Rottweiler,Mixed Breed
84,44728951,Sutcliffe,adoptable,True,False,None,False,True,None,US,CO,Littleton,Male,Baby,Boxer,Shepherd
85,44727098,41708934,adoptable,False,False,None,False,False,328 Furman Hall Road,US,SC,Greenville,Female,Adult,Retriever,Mixed Breed
86,44726012,ARCHIE,adoptable,False,False,None,False,False,3599 NW 79 Avenue Doral,US,FL,Miami,Male,Adult,Yorkshire Terrier,Mixed Breed
87,44728279,A517489,adoptable,False,False,None,False,False,3647 Cornucopia Way,US,CA,Modesto,Male,Young,Dachshund,None
88,44725885,Viktorbear,adoptable,True,True,None,False,True,1250 North River Drive,US,MN,Mankato,Male,Adult,Rottweiler,Mixed Breed
89,44728940,Harrison,adoptable,True,False,None,False,True,None,US,CO,Littleton,Male,Baby,Boxer,Shepherd
90,44726462,Bella,adoptable,True,False,None,False,False,7 E. George Street,US,WA,Walla Walla,Female,Young,Retriever,Mixed Breed
91,44726036,BELLE,adoptable,False,False,None,False,False,3599 NW 79 Avenue Doral,US,FL,Miami,Female,Adult,Yorkshire Terrier,Mixed Breed
92,44728038,KIKO,adoptable,False,False,None,False,False,2769 Conroy Road,US,FL,Orlando,Male,Young,Dachshund,None
93,44724866,SIMONE,adoptable,True,False,None,False,False,305 - 25th Street West,US,FL,Palmetto,Female,Adult,Rottweiler,Mixed Breed
94,44728942,Lennon,adoptable,True,False,None,False,True,None,US,CO,Littleton,Male,Baby,Boxer,Shepherd
95,44725304,Jasper Jacob,adoptable,True,False,None,False,True,3901 Martha Truman Road.,US,MO,Kansas City,Male,Adult,Retriever,Mixed Breed
96,44725550,Macho SDR in TX,adoptable,True,False,None,False,True,None,US,RI,Providence,Male,Adult,Yorkshire Terrier,Mixed Breed
97,44728035,BENTLY,adoptable,False,False,None,False,False,2769 Conroy Road,US,FL,Orlando,Male,Adult,Dachshund,None
98,44723912,Lily the Mini Rotty!,adoptable,True,False,None,False,True,None,US,PA,Media,Female,Young,Rottweiler,Mixed Breed
99,44728908,APOLLO,adoptable,True,False,None,False,False,3750 Brown Station Rd,US,MD,Upper Marlboro,Male,Young,Boxer,Shepherd